//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.jackleeentertainment.testrecyclerviewproject;

import android.app.Application;
import android.content.Context;
import android.net.Uri;
import android.util.Log;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;

/**
 * Application class responsible for initializing singletons and other common components.
 */
public class App extends Application {

    private final static String TAG = Application.class.getSimpleName();
    private static Context appContext;

    //User Profile
    public static Uri UrlFbaseBasicPhoto;

    //User Login
    public static String token;

    //Firebase Ref

    public static FirebaseDatabase firebaseDatabase;
    public static DatabaseReference fbaseDbRef;
    public static FirebaseStorage firebaseStorage;
    public static StorageReference fbaseStorageRef;

    public static boolean GIVEN_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGES = false;
    public static int CURRENTFRAGMENT_MAINACTIVITY = 0;


    public static Application getInstance() {
        return new App();
    }


    @Override
    public void onCreate() {
        Log.d(TAG, "Application.onCreate - Initializing application...");
        super.onCreate();
        appContext = getApplicationContext();
        initFbaseDatabase();
        initFbaseDatabaseRef();
        initFbaseStorage();
        Log.d(TAG, "Application.onCreate - Application initialized OK");
    }


    public static void initFbaseDatabase() {
        Log.d(TAG, "initFbaseDatabase()");
        firebaseDatabase = FirebaseDatabase.getInstance();
        firebaseDatabase.setPersistenceEnabled(true);
        Log.d(TAG, "firebaseDatabase.getApp().getMname() :" + firebaseDatabase.getApp().getName());
    }

    public static void initFbaseDatabaseRef() {
        Log.d(TAG, "initFbaseDatabaseRef()");
        fbaseDbRef = firebaseDatabase.getReference();
    }

    public static void initFbaseStorage() {
        firebaseStorage = FirebaseStorage.getInstance();
        fbaseStorageRef = firebaseStorage.getReferenceFromUrl("gs://project-5788136259447833395.appspot.com");
        Log.d(TAG, "firebaseStorage.getApp().getMname() :" + firebaseStorage.getApp().getName());

    }


    public static Context getContext() {
        return appContext;
    }


}
